### ISSUE TITLE
GetX

### ISSUE THREAD

**Issue by ichenwanbing** [xieyezi/flutter-shopping-AiRi#11]
你好，感谢开源。看到后续计划用GetX重构，请问有在进行了吗？大概什么时候更新呢？想学习GetX的成熟项目

**Comment by xieyezi** [comment]
@ichenwanbing 
感谢关注！
getx版本的重构时间，战线可能会比较长，可以持续关注。
另外如果你想学习成熟的`getx开发方式`,可以看[这里](https://github.com/xieyezi/flutter-getx-template)
再次谢谢支持！

**Comment by NicodeLee** [comment]
希望不忙的时候能更新一下，开一个分支慢慢重构一部分getx也是可以的，学习用能看到部分模块替换已经足够了。
