### ISSUE TITLE
文件路径问题

### ISSUE THREAD

**Issue by masterchen** [xieyezi/flutter-shopping-AiRi#12]
直接导入到flutter2.6，可能跟版本没有关系。 错误是 会报找不到文件，请问为何会有 “package:”  和“'package:AiRi”   如何快速消除，谢谢！
Target of URI doesn't exist: 'package:flutter/material.dart'.
Try creating the file referenced by the URI, or Try using a URI for a file that does exist.darturi_does_not_exist

Target of URI doesn't exist: 'package:AiRi/pages/shopping_cart/store/shopping_cart_provider.dart'.
Try creating the file referenced by the URI, or Try using a URI for a file that does exist.darturi_does_not_exist

**Comment by xieyezi** [comment]
@masterchen 你需要修改包名，你搜一下应该很快解决。
不过我建议的使用方式是：你新建一个新的flutter项目，然后将代码复制到你新建的项目中
