### ISSUE TITLE
无法运行，报错

### ISSUE THREAD

**Issue by yusinan0119** [xieyezi/flutter-shopping-AiRi#9]
Error output from CocoaPods:
↳
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin20/rbconfig.rb:229: warning: Insecure world writable dir /usr/local/sbin in PATH, mode 040777

Error running pod install
Error launching application on iPhone 12.

**Comment by xieyezi** [comment]
@yusinan0119 抱歉，还没升级到flutter 2.0的版本，目前支持的版本是flutter v1.22.4 stable

**Comment by xieyezi** [comment]
@yusinan0119 如果不是因为flutter版本的原因，建议删除ios目录下的Podfile.lock重新 `pod install`

**Comment by yusinan0119** [comment]
感谢回复，刚试了一下，重新install依然不行。期待更新适配2.0谢谢

**Comment by xieyezi** [comment]
@yusinan0119  已迁移至flutter v2版本。sdk 版本如下：

```
Flutter 2.2.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b22742018b (10 days ago) • 2021-05-14 19:12:57 -0700
Engine • revision a9d88a4d18
Tools • Dart 2.13.0
```

**Comment by yusinan0119** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    谢谢指导！
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                343838823
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2021年05月25日 ***@***.***> 写道： 




@yusinan0119  已迁移至flutter v2版本。sdk 版本如下：

Flutter 2.2.0 • channel stable • https://github.com/flutter/flutter.git

Framework • revision b22742018b (10 days ago) • 2021-05-14 19:12:57 -0700

Engine • revision a9d88a4d18

Tools • Dart 2.13.0





—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
